// Get Post Data
export const LINKEDIN_POST_PENDING = "LINKEDIN_POST_PENDING";
export const LINKEDIN_POST_FULLFILLED = "LINKEDIN_POST_FULLFILLED";
export const LINKEDIN_POST_REJECTED = "LINKEDIN_POST_FULLFILLED";

// Create Post Data
export const LINKEDIN_CREATE_PENDING = "LINKEDIN_CREATE_PENDING";
export const LINKEDIN_CREATE_FULLFILLED = "LINKEDIN_CREATE_FULLFILLED";
export const LINKEDIN_CREATE_REJECTED = "LINKEDIN_CREATE_FULLFILLED";

// Delete Post Data
export const LINKEDIN_DELETE_PENDING = "LINKEDIN_DELETE_PENDING";
export const LINKEDIN_DELETE_FULLFILLED = "LINKEDIN_DELETE_FULLFILLED";
export const LINKEDIN_DELETE_REJECTED = "LINKEDIN_DELETE_REJECTED";

// Update Post Data
export const LINKEDIN_UPDATE_PENDING = "LINKEDIN_UPDATE_PENDING";
export const LINKEDIN_UPDATE_FULLFILLED = "LINKEDIN_UPDATE_FULLFILLED";
export const LINKEDIN_UPDATE_REJECTED = "LINKEDIN_UPDATE_REJECTED";
