// Get Post Data
export const LINKEDIN_POST_PENDING = "LINKEDIN_POST_PENDING";
export const LINKEDIN_POST_FULLFILLED = "LINKEDIN_POST_FULLFILLED";
export const LINKEDIN_POST_REJECTED = "LINKEDIN_POST_FULLFILLED";

// Create Post Data
export const LINKEDIN_CREATE_PENDING = "LINKEDIN_CREATE_PENDING";
export const LINKEDIN_CREATE_FULLFILLED = "LINKEDIN_CREATE_FULLFILLED";
export const LINKEDIN_CREATE_REJECTED = "LINKEDIN_CREATE_FULLFILLED";
